name: "External API Action"

description: "Use an external API to retrieve a joke and display it "

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API
    
runs:
  using: "node12"
  main: "main.js"
  
