name: JS Actions

on: [push]

jobs:
   action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
       
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Bhavana"
          
      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes
        
      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
         repo-token: ${{secrets.GITHUB_TOKEN}}
         joke: ${{steps.jokes.output.joke-output}}
         
        


